import argparse
from pathlib import Path

from .constants import DEFAULT_QUESTIONNAIRE, ROOT
from .figures import plot_phase_metric_boxplots, plot_top2_burden
from .head_motion import (
    aggregate_subject_level,
    clean_head_motion_directory,
    compute_phase_metrics_from_clean_dir,
)
from .questionnaire import (
    build_participant_table,
    build_top2_burden,
    load_questionnaire,
)
from .rating_time import extract_rating_events, summarize_rating_events
from .statistics import run_phase_statistics
from .utils import ensure_dir


CLEAN_SOURCES = {
    "clean24": "clean_data",
    "clean40": "clean_data2",
}

RAW_SOURCES = {
    "raw24": "raw_data",
    "raw32": "raw_data1",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the cleaned Interruption360 reproduction pipeline.")
    parser.add_argument("--root", type=Path, default=ROOT, help="Project root folder.")
    parser.add_argument(
        "--source",
        choices=sorted([*CLEAN_SOURCES, *RAW_SOURCES]),
        default="clean24",
        help="Head-motion source. clean24 matches the trajectory metrics available in this folder.",
    )
    parser.add_argument("--out-dir", type=Path, default=ROOT / "repro_outputs", help="Output directory.")
    parser.add_argument(
        "--questionnaire",
        type=Path,
        default=DEFAULT_QUESTIONNAIRE,
        help="After-test questionnaire workbook.",
    )
    parser.add_argument("--no-figures", action="store_true", help="Skip figure rendering.")
    return parser.parse_args()


def _resolve_clean_dir(root: Path, out_dir: Path, source: str) -> Path:
    if source in CLEAN_SOURCES:
        return root / CLEAN_SOURCES[source]
    raw_dir = root / RAW_SOURCES[source]
    clean_dir = out_dir / "head_motion" / f"cleaned_from_{source}"
    clean_head_motion_directory(raw_dir, clean_dir)
    return clean_dir


def _write_scope_report(
    out_path: Path,
    source: str,
    clean_dir: Path,
    phase_metrics,
    questionnaire_n: int,
    questionnaire_path: Path,
    saliency_path: Path,
) -> None:
    users = phase_metrics["UserID"].nunique()
    trials = phase_metrics[["UserID", "VideoID"]].drop_duplicates().shape[0]
    report = f"""# Paper Reproduction Scope

This report is intentionally strict: the main pipeline only keeps analyses that appear in `/Users/liangyu/Desktop/rebuttal_version.pdf`.

## Recomputed from files in this folder

- Section 4.1 / Figure 4 trajectory metrics: computed from `{clean_dir}` via source `{source}`.
  - Actual head-motion N in this source: {users} users.
  - User-video trials found: {trials}.
  - Metrics: normalized angular velocity, median angular velocity, FTR, and SER.
- Section 3.5 participant questionnaire summaries and Section 4.3 / Figure 6 Top-2 burden: computed from `{questionnaire_path}`.
  - Actual questionnaire N: {questionnaire_n} users.
- UI active interval summaries are exported from the available cleaned frame logs as a data check only.
  - The exact response-log source needed to recompute the paper's Figure 2 values is not present in this folder.

## Not recomputed because the needed source files are absent

- Section 4.2 / Figure 5 and Table 2 saliency model comparison.
  - The paper reports four model families and N=40.
  - The current `{saliency_path}` file does not contain model identifiers or the complete N=40 cross-model results, so the pipeline does not fabricate Table 2.

## Removed from the main reproduction

- Composite QoE scores, QoE radar plots, and subjective-objective correlation analyses are not part of the paper PDF and are therefore not generated by this pipeline.
"""
    out_path.write_text(report, encoding="utf-8")


def run_pipeline(
    root: Path = ROOT,
    source: str = "clean24",
    out_dir: Path | None = None,
    questionnaire_path: Path | None = None,
    make_figures: bool = True,
) -> dict[str, Path]:
    root = root.resolve()
    out_dir = (out_dir or root / "repro_outputs").resolve()
    questionnaire_path = (questionnaire_path or DEFAULT_QUESTIONNAIRE).resolve()
    saliency_path = (root / "users1_24_metrics_compact_video1_10.csv").resolve()

    paths: dict[str, Path] = {}
    head_dir = ensure_dir(out_dir / "head_motion")
    question_dir = ensure_dir(out_dir / "questionnaire")
    rating_dir = ensure_dir(out_dir / "rating_time")
    figure_dir = ensure_dir(out_dir / "figures")

    clean_dir = _resolve_clean_dir(root, out_dir, source)
    phase_metrics = compute_phase_metrics_from_clean_dir(clean_dir)
    paths["phase_metrics"] = head_dir / "phase_metrics.csv"
    phase_metrics.to_csv(paths["phase_metrics"], index=False)

    subject_level = aggregate_subject_level(phase_metrics)
    paths["subject_phase_metrics"] = head_dir / "subject_phase_metrics.csv"
    subject_level.to_csv(paths["subject_phase_metrics"], index=False)

    normality, global_tests, pairwise = run_phase_statistics(subject_level)
    paths["stats_normality"] = head_dir / "stats_normality_shapiro.csv"
    paths["stats_global"] = head_dir / "stats_global_friedman.csv"
    paths["stats_pairwise"] = head_dir / "stats_pairwise_holm.csv"
    normality.to_csv(paths["stats_normality"], index=False)
    global_tests.to_csv(paths["stats_global"], index=False)
    pairwise.to_csv(paths["stats_pairwise"], index=False)

    events = extract_rating_events(clean_dir)
    for name, table in summarize_rating_events(events).items():
        path = rating_dir / f"{name}.csv"
        table.to_csv(path, index=False)
        paths[name] = path

    questionnaire = load_questionnaire(questionnaire_path)
    participants = build_participant_table(questionnaire)
    top2 = build_top2_burden(questionnaire)
    paths["participants"] = question_dir / "participants.csv"
    paths["top2_burden"] = question_dir / "top2_burden.csv"
    participants.to_csv(paths["participants"], index=False)
    top2.to_csv(paths["top2_burden"], index=False)

    paths["scope_report"] = out_dir / "scope_report.md"
    _write_scope_report(
        paths["scope_report"],
        source,
        clean_dir.resolve(),
        phase_metrics,
        len(questionnaire.valid),
        questionnaire_path,
        saliency_path,
    )

    if make_figures:
        paths["phase_boxplot"] = figure_dir / "phase_metric_boxplots.pdf"
        plot_phase_metric_boxplots(subject_level, paths["phase_boxplot"])
        paths["top2_burden_plot"] = figure_dir / "top2_burden.pdf"
        plot_top2_burden(top2, paths["top2_burden_plot"])

    return paths


def main() -> None:
    args = parse_args()
    paths = run_pipeline(
        root=args.root,
        source=args.source,
        out_dir=args.out_dir,
        questionnaire_path=args.questionnaire,
        make_figures=not args.no_figures,
    )
    print("[INFO] Reproduction pipeline finished.")
    for name, path in paths.items():
        print(f"[INFO] {name}: {path}")


if __name__ == "__main__":
    main()
